### ISSUE TITLE
feat(kona-exex): Basic ExEx Installation & Routing

### ISSUE THREAD

**Issue by refcell** [paradigmxyz/op-rs#3]
## Overview

> [!NOTE]
>
> Based on https://github.com/paradigmxyz/reth-exex-examples/pull/12

This is a preliminary task to set up the `kona-exex`. The below files are intended to be placed in `bin/kona-exex/src/`.

The cargo manifest will also need to be updated with dependencies.

```toml
# Reth Dependencies
reth = { git = "https://github.com/paradigmxyz/reth" }
reth-exex = { git = "https://github.com/paradigmxyz/reth" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth" }

# OP Stack Dependencies
superchain-registry = { version = "0.2.6", default-features = false }
kona-derive = { git = "https://github.com/ethereum-optimism/kona", branch = "main", features = ["online", "serde"] }

# Needed for compatibility with kona's ChainProvider trait
anyhow = { version = "1.0.86", default-features = false }
```

### `main.rs`

Set up the `main.rs` to run an `EthereumNode` and install the `kona-exex`.

```rust
use eyre::Result;
use reth::cli::Cli;
use reth_node_ethereum::EthereumNode;

mod kona;
use kona::KonaExEx;

mod cli;
use cli::KonaArgExt;

fn main() -> Result<()> {
    Cli::<KonaArgsExt>::parse().run(|builder, args| async move {
        let node = EthereumNode::default();
        let kona = move |ctx| async { Ok(KonaExEx::new(ctx, args).await.start()) };
        let handle = builder.node(node).install_exex("Kona", kona).launch().await?;
        handle.wait_for_node_exit().await
    })
}
```

### `kona.rs`

Implement the primary `KonaExEx` object. This controls most of the execution extension.

```rust
use eyre::Result;
use std::sync::Arc;
use kona_derive::types::RollupConfig;
use reth_exex::ExExContext;
use reth_node_api::FullNodeComponents;
use super::KonaArgsExt;

#[derive(Debug)]
pub(crate) struct KonaExEx<Node: FullNodeComponents> {
    // ...
}

impl<Node: FullNodeComponents> KonaExEx<Node> {
    /// Creates a new instance of the Kona Execution Extension.
    pub async fn new(ctx: ExExContext<Node>, args: KonaArgsExt, cfg: Arc<RollupConfig>) -> Self {
        // ...
    }

    /// Starts the Kona Execution Extension loop.
    pub async fn start(mut self) -> Result<()> {
        // ...
    }
}
```

### `cli.rs`

```rust
//! CLI Extension module for Kona

use std::path::PathBuf;

use clap::Args;
use reqwest::Url;

pub const DEFAULT_L2_CHAIN_ID: u64 = 10;

pub const DEFAULT_L2_RPC_URL: &str = "https://optimism.llamarpc.com/";

pub const DEFAULT_BEACON_CLIENT_URL: &str = "http://localhost:5052/";

#[derive(Debug, Clone, Args)]
pub(crate) struct KonaArgsExt {
  // ...
}
```
